spring:
  application:
    name: nivel2-springai

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.7
          max-tokens: 512

server:
  port: 8081

logging:
  level:
    org.springframework.ai: DEBUG
    com.universidad: INFO